baseURL = "https://blog.arendsyl.com/"
languageCode = "en_us"
title = "Blog ArendSyl"
theme = "soho"

enableInlineShortcodes = true

summarylength = 10
enableEmoji = true

[params]
author = "Arend'Syl"
description = "IT stuff and maybe more"

## Set one of:
# gravatar = "soho@example.com"
profilePicture = "images/avatar.jpg"

copyright = "Kaiser Jean-Baptiste"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

## Set custom theme color.
themeColor = "#0D47A1"

## Set custom CSS and/or JS to override site defaults.
customCss = ["css/blog.css"]
customJs = ["js/blog.js"]

  ## Set as many as you want.
  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/jean-baptiste-kaiser-328524188"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/arendsyl"

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Categories"
  weight = 200
  identifier = "categories"
  url = "/categories/"

  [[menu.main]]
  name = "Tags"
  weight = 200
  identifier = "tags"
  url = "/tags/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 300
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  identifier = "contact"
  weight = 300
  url = "/contact/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4
